# Generated by Django 3.1.6 on 2021-02-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='')),
                ('detected_image', models.ImageField(upload_to='')),
                ('detected_base64', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('effect_percentage', models.DecimalField(decimal_places=6, max_digits=9)),
                ('boxes', models.TextField()),
                ('scores', models.TextField()),
                ('classes', models.TextField()),
                ('num', models.TextField()),
            ],
        ),
    ]
